---
driver:
  name: vagrant
  vagrnatfiles:
    - Vagrantfile.rb
  customize:
    memory: 2048

provisioner:
  name: chef_zero
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: true

verifier:
  name: inspec

platforms:
#  - name: ubuntu-16.04
  - name: centos/7

suites:
  - name: master
    run_list:
      - recipe[kubeadm::master]
    driver:
      vm_hostname: master.vagrant.test
      network:
        - ["private_network", {ip: "172.28.128.200"}]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
  - name: node01
    run_list:
      - recipe[kubeadm::node]
    driver:
      vm_hostname: node01.vagrant.test
      network:
        - ["private_network", {ip: "172.28.128.201"}]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
  - name: node02
    run_list:
      - recipe[kubeadm::node]
    driver:
      vm_hostname: node02.vagrant.test
      network:
        - ["private_network", {ip: "172.28.128.202"}]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
